services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\Presentation\Console\Core\User\CreateUserConsoleCommand:
    tags: [ 'console.command' ]

  App\Presentation\Console\Core\User\ChangeUserPasswordConsoleCommand:
    tags: [ 'console.command' ]

  App\Presentation\Console\Question\Profile\CreateProfileConsoleCommand:
    tags: [ 'console.command' ]

  App\Presentation\Console\Question\Question\CreateQuestionConsoleCommand:
    tags: [ 'console.command' ]

  App\Presentation\Console\Question\Answer\CreateAnswerConsoleCommand:
    tags: [ 'console.command' ]

  App\Presentation\Http\UserInterface\Core\Controller\:
    resource: '../../Http/UserInterface/Core/Controller/'
    tags: ['controller.service_arguments']